## 5.1 Pandas란?

- pandas는 <b>"python data analysis"</b>의 약자입니다.
> pandas는 정형 데이터 처리에 특화되어 있다.

- pandas 역시 다양한 머신러닝 라이브러리들에 의존성을 가지고 있습니다.
> scikit-learn, scipy, statsmodel, tensorflow, pytorch, ...


- 간단하게 생각하면, **python에서 excel의 기능을 사용**할 수 있게 됩니다.
> pandas = python + excel // pandas & excel // pandas VS MS Excel

- 하지만, pandas는 numpy array를 베이스로 지원하며 파이썬과 함께 강력한 시너지를 내기 때문에, 엑셀 그 이상의 퍼포먼스를 냅니다.
> pandas가 Excel에 비해 고성능 데이터처리에 적합하다.

![numpy_data_type](../images/pandas/dataframe.png)

- Pandas 라이브러리에서 기본적으로 데이터를 다루는 단위는 DataFrame입니다. 흔히 알고있는 spreadsheet와 같은 개념입니다.


- 이러한 형태의 데이터는 Structured Data 또는 Panel Data 또는 Tabular Data라고 부릅니다.


- pandas를 공부한다는 것은 결국 dataframe의 사용법을 익히고 활용하는 방법을 배운다는 것과 같습니다.


- pandas를 잘 활용하면 대부분의 structured data를 자유자재로 다룰 수 있게 됩니다.

![pandas_files](../images/pandas/pandas_files.png)

## 5.2. Pandas의 기본 자료구조(Series, DataFrame)

In [1]:
# pandas 라이브러리를 불러옵니다. pd를 약칭으로 사용합니다.
import pandas as pd
import numpy as np
print(pd.__version__) # pandas version 확인.

1.3.5

- DataFrame은 2차원 테이블이고, 테이블의 한 줄(행/열)을 Series라고 합니다.


- Series의 모임이 곧, DataFrame이 됩니다.

In [2]:
# s는 1, 3, 5, np.nan, 6, 8을 원소로 가지는 pandas.Series
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

- pandas는 date_range라는 함수를 통해, 날짜정보를 쉽게 생성해주는 객체도 제공합니다.

In [3]:
# 20210101부터 6일간의 날짜 범위를 생성하는 pandas.date_range
dates = pd.date_range('20210101', periods=6)
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
# 6x4 행렬에 -1에서 1 사이의 랜덤한 숫자를 가지는 원소를 가지고, index열은 dates, 
# 나머지 coulmns은 순서대로 A, B, C, D로 하는 DataFrame 생성
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['A', 'B', 'C', 'D'])
df

                   A         B         C         D
2021-01-01  0.682536  1.094228 -0.443147 -2.178491
2021-01-02 -0.089488  0.013657 -1.273014  1.043680
2021-01-03  0.616340 -0.051461 -0.883844 -0.061446
2021-01-04  0.373785 -0.424947 -1.756662  1.978335
2021-01-05  0.399235  0.833395 -1.443849  0.086572
2021-01-06 -0.721418  0.019740  1.981655  0.784544

## 5.3. Dataframe 기초 method

In [5]:
# dataframe의 맨 위 다섯줄을 보여주는 head()
df.head()

                   A         B         C         D
2021-01-01  0.682536  1.094228 -0.443147 -2.178491
2021-01-02 -0.089488  0.013657 -1.273014  1.043680
2021-01-03  0.616340 -0.051461 -0.883844 -0.061446
2021-01-04  0.373785 -0.424947 -1.756662  1.978335
2021-01-05  0.399235  0.833395 -1.443849  0.086572

In [6]:
# 3줄
df.head(3)
df.tail(3)

                   A         B         C         D
2021-01-04  0.373785 -0.424947 -1.756662  1.978335
2021-01-05  0.399235  0.833395 -1.443849  0.086572
2021-01-06 -0.721418  0.019740  1.981655  0.784544

In [7]:
# dataframe index
df.index

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [8]:
# dataframe columns
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [9]:
# dataframe values
df.values

array([[ 0.68253621,  1.09422817, -0.44314695, -2.17849124],
       [-0.08948786,  0.01365738, -1.273014  ,  1.04368022],
       [ 0.61634008, -0.05146119, -0.88384382, -0.06144626],
       [ 0.37378455, -0.42494709, -1.75666203,  1.97833514],
       [ 0.39923521,  0.83339519, -1.4438489 ,  0.08657223],
       [-0.72141765,  0.01973961,  1.98165531,  0.78454371]])

In [10]:
# dataframe에 대한 전체적인 요약정보를 보여줍니다. index, columns, null/not-null/dtype/memory usage가 표시됩니다.
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2021-01-01 to 2021-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes

In [11]:
# dataframe에 대한 전체적인 통계정보를 보여줍니다.
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.210165  0.247435 -0.636477  0.275532
std    0.530711  0.584524  1.361251  1.408558
min   -0.721418 -0.424947 -1.756662 -2.178491
25%    0.026330 -0.035182 -1.401140 -0.024442
50%    0.386510  0.016698 -1.078429  0.435558
75%    0.562064  0.629981 -0.553321  0.978896
max    0.682536  1.094228  1.981655  1.978335

In [12]:
# column a를 기준으로 내림차순 정렬
df.sort_values(by='A', ascending=False).head(3) # column a를 기준으로 값이 가장 큰 top 3를 보여주세요.

                   A         B         C         D
2021-01-01  0.682536  1.094228 -0.443147 -2.178491
2021-01-03  0.616340 -0.051461 -0.883844 -0.061446
2021-01-05  0.399235  0.833395 -1.443849  0.086572

## 5.4. DataFrame Indexing

> Indexing : 데이터에서 어떤 특정 조건을 만족하는 원소를 찾는 방법.

> 전체 DataFrame에서 조건에 만족하는 데이터를 쉽게 찾아서 조작할 때 유용하게 사용할 수 있습니다.

In [13]:
# pandas dataframe은 column 이름을 이용하여 기본적인 Indexing이 가능합니다.
# column A를 indexing
df["A"] # dataframe에 바로 indexing을 사용하면, column을 찾습니다. == dictionary의 indexing과 같다.
# == "key"를 indexing. == "key" == "column"

# df["2021-01-01"]

2021-01-01    0.682536
2021-01-02   -0.089488
2021-01-03    0.616340
2021-01-04    0.373785
2021-01-05    0.399235
2021-01-06   -0.721418
Freq: D, Name: A, dtype: float64

In [14]:
# 특정날짜를 통한 Indexing
df.loc['2021-01-03'] # pd.Series

A    0.616340
B   -0.051461
C   -0.883844
D   -0.061446
Name: 2021-01-03 00:00:00, dtype: float64

In [15]:
# 특정 위치를 통한 indexing
df.iloc[2]

A    0.616340
B   -0.051461
C   -0.883844
D   -0.061446
Name: 2021-01-03 00:00:00, dtype: float64

In [16]:
# dataframe에서 slicing을 이용하면 row 단위로 잘려나옵니다.
# 앞에서 3줄을 slicing 합니다.
df[:3] # 숫자를 그냥 사용하게되면, index(양의 정수)를 이용한 slicing

                   A         B         C         D
2021-01-01  0.682536  1.094228 -0.443147 -2.178491
2021-01-02 -0.089488  0.013657 -1.273014  1.043680
2021-01-03  0.616340 -0.051461 -0.883844 -0.061446

In [17]:
# df에서 index value를 기준으로 indexing도 가능합니다. (여전히 row 단위)
# 20210102부터 20210104까지 잘라봅니다. # index의 값을 사용하게되면 Index를 이용한 slicing
df['2021-01-02':'2021-01-04']

                   A         B         C         D
2021-01-02 -0.089488  0.013657 -1.273014  1.043680
2021-01-03  0.616340 -0.051461 -0.883844 -0.061446
2021-01-04  0.373785 -0.424947 -1.756662  1.978335

In [18]:
df.loc['2021-01-02']

A   -0.089488
B    0.013657
C   -1.273014
D    1.043680
Name: 2021-01-02 00:00:00, dtype: float64

In [19]:
# df.loc는 특정값을 기준으로 indexing합니다. (key - value)
# 2013-01-01값을 가지는 row를 가져옵니다.
df.loc[dates[0]] # df.loc[]

A    0.682536
B    1.094228
C   -0.443147
D   -2.178491
Name: 2021-01-01 00:00:00, dtype: float64

In [20]:
# df.loc에 2차원 indexing도 가능합니다. [:, ["A", "B"]]의 의미는 모든 row에 대해서 columns는 A, B만 가져오라는 의미입니다.
df.loc[:, ["A", "C"]] # dataframe에서 2차원 indexing을 할 때, column들은 리스트로 넘겨줄 수 있다.

                   A         C
2021-01-01  0.682536 -0.443147
2021-01-02 -0.089488 -1.273014
2021-01-03  0.616340 -0.883844
2021-01-04  0.373785 -1.756662
2021-01-05  0.399235 -1.443849
2021-01-06 -0.721418  1.981655

In [21]:
# 이번엔 slicing을 통해 특정 row중에서 columns는 A, B
df.loc['2021-01-03':'2021-01-05', ['A', 'C']]

                   A         C
2021-01-03  0.616340 -0.883844
2021-01-04  0.373785 -1.756662
2021-01-05  0.399235 -1.443849

In [22]:
# 특정 row를 index값을 통한 indexing
df.loc['2021-01-02', ['A', 'B']]

A   -0.089488
B    0.013657
Name: 2021-01-02 00:00:00, dtype: float64

In [23]:
# 2차원 리스트 indexing과 같은 원리가 되었습니다.
df.loc['2021-01-01', 'C'] # 특정 row(index)에 특정 column값.

-0.4431469468581762

In [24]:
# df.iloc는 정수를 이용한 indexing과 같습니다.(row 기준) 3은 4번째를 의미합니다.
df.iloc[3]

A    0.373785
B   -0.424947
C   -1.756662
D    1.978335
Name: 2021-01-04 00:00:00, dtype: float64

In [25]:
# iloc로 2차원 indexing을 하게되면, row 기준으로 index 3,4를 가져오고 column 기준으로 0, 1을 가져옵니다.
df.iloc[3:5, 0:2] # df.iloc의 indexing은 numpy array의 2차원 index과 동일해진다.

                   A         B
2021-01-04  0.373785 -0.424947
2021-01-05  0.399235  0.833395

In [26]:
# slicing이 아닌 직접 리스트 형태로 기재하는 indexing
df.iloc[[1, 2, 4], [0, 3]] # filtering.

                   A         D
2021-01-02 -0.089488  1.043680
2021-01-03  0.616340 -0.061446
2021-01-05  0.399235  0.086572

In [27]:
# Q. 2차원 indexing에 뒤에가 : 면 어떤 의미일까요?
df.iloc[1:3, :]

                   A         B         C         D
2021-01-02 -0.089488  0.013657 -1.273014  1.043680
2021-01-03  0.616340 -0.051461 -0.883844 -0.061446

In [28]:
df.iloc[:, 1:3] # numpy array의 2차원 indexing과 같다.

                   B         C
2021-01-01  1.094228 -0.443147
2021-01-02  0.013657 -1.273014
2021-01-03 -0.051461 -0.883844
2021-01-04 -0.424947 -1.756662
2021-01-05  0.833395 -1.443849
2021-01-06  0.019740  1.981655

In [29]:
df

                   A         B         C         D
2021-01-01  0.682536  1.094228 -0.443147 -2.178491
2021-01-02 -0.089488  0.013657 -1.273014  1.043680
2021-01-03  0.616340 -0.051461 -0.883844 -0.061446
2021-01-04  0.373785 -0.424947 -1.756662  1.978335
2021-01-05  0.399235  0.833395 -1.443849  0.086572
2021-01-06 -0.721418  0.019740  1.981655  0.784544

In [30]:
# pandas는 fancy indexing을 지원합니다. (사실 numpy에서 지원하기 때문에 pandas도 지원합니다.)
# fancy indexing이란 조건문을 통해 indexing을 할 수 있는 방법으로 True와 False를 원소로 하는 리스트를 통해 masking하는 원리로 동작합니다.
# column A에 있는 원소들중에 0보다 큰 데이터를 가져옵니다.
df['A'] > 0

2021-01-01     True
2021-01-02    False
2021-01-03     True
2021-01-04     True
2021-01-05     True
2021-01-06    False
Freq: D, Name: A, dtype: bool

In [31]:
df.loc[:, 'A'] > 0

2021-01-01     True
2021-01-02    False
2021-01-03     True
2021-01-04     True
2021-01-05     True
2021-01-06    False
Freq: D, Name: A, dtype: bool

In [32]:
df[df["A"] > 0]["B"]

2021-01-01    1.094228
2021-01-03   -0.051461
2021-01-04   -0.424947
2021-01-05    0.833395
Name: B, dtype: float64

In [33]:
# fancy indexing
df['A'][df["A"] > 0] # dataframe # chain indexing : indexing이 앞에서부터 뒤로 쭉 순서대로 적용됩니다.

2021-01-01    0.682536
2021-01-03    0.616340
2021-01-04    0.373785
2021-01-05    0.399235
Name: A, dtype: float64

In [34]:
df[df < 0] = 0
df

                   A         B         C         D
2021-01-01  0.682536  1.094228  0.000000  0.000000
2021-01-02  0.000000  0.013657  0.000000  1.043680
2021-01-03  0.616340  0.000000  0.000000  0.000000
2021-01-04  0.373785  0.000000  0.000000  1.978335
2021-01-05  0.399235  0.833395  0.000000  0.086572
2021-01-06  0.000000  0.019740  1.981655  0.784544

In [35]:
#df[df > 0]
df[df > 0]

                   A         B         C         D
2021-01-01  0.682536  1.094228       NaN       NaN
2021-01-02       NaN  0.013657       NaN  1.043680
2021-01-03  0.616340       NaN       NaN       NaN
2021-01-04  0.373785       NaN       NaN  1.978335
2021-01-05  0.399235  0.833395       NaN  0.086572
2021-01-06       NaN  0.019740  1.981655  0.784544

In [36]:
df2 = df.copy() # dataframe 하나를 복사합니다. 정말 말그대로 복사합니다.

In [37]:
# dataframe은 dictionary와 비슷한 방식으로 assignment가 가능합니다.
# df에 ['one', 'one','two','three','four','three'] 리스트를 column의 value로 하는 column E를 추가합니다.
df2['E'] = ['one', 'one','two','three','four','three'] # 만약 이미 column E가 존재한다면 update.
df2

                   A         B         C         D      E
2021-01-01  0.682536  1.094228  0.000000  0.000000    one
2021-01-02  0.000000  0.013657  0.000000  1.043680    one
2021-01-03  0.616340  0.000000  0.000000  0.000000    two
2021-01-04  0.373785  0.000000  0.000000  1.978335  three
2021-01-05  0.399235  0.833395  0.000000  0.086572   four
2021-01-06  0.000000  0.019740  1.981655  0.784544  three

In [38]:
# df.isin은 해당 value들이 들어있는 row에 대해선 True를 가지는 Series를 리턴한다.
df2['E'].isin(['two','four'])

2021-01-01    False
2021-01-02    False
2021-01-03     True
2021-01-04    False
2021-01-05     True
2021-01-06    False
Freq: D, Name: E, dtype: bool

In [39]:
df2[df2['E'].isin(['two','four'])]

                   A         B    C         D     E
2021-01-03  0.616340  0.000000  0.0  0.000000   two
2021-01-05  0.399235  0.833395  0.0  0.086572  four

In [40]:
df

                   A         B         C         D
2021-01-01  0.682536  1.094228  0.000000  0.000000
2021-01-02  0.000000  0.013657  0.000000  1.043680
2021-01-03  0.616340  0.000000  0.000000  0.000000
2021-01-04  0.373785  0.000000  0.000000  1.978335
2021-01-05  0.399235  0.833395  0.000000  0.086572
2021-01-06  0.000000  0.019740  1.981655  0.784544

## 5.5. 외부 데이터 읽고 쓰기

In [41]:
# data 폴더에 있는 iris.csv를 불러오자.
import pandas as pd
data = pd.read_csv("data/Iris.csv")
data

FileNotFoundError: ignored

In [ ]:
# Species column을 숫자로 바꿔보자.
set(data["Species"])

In [ ]:
data.loc[data["Species"] == "Iris-setosa", "Species"] = 0
data.loc[data["Species"] == "Iris-versicolor", "Species"] = 1
data.loc[data["Species"] == "Iris-virginica", "Species"] = 2
data

In [ ]:
# 바꾼 Dataframe을 Iris_edited.csv 로 저장하자.
data.to_csv("data/Iris_edited.csv")

In [ ]:
# 다른 파일도 불러오자.
import pandas as pd
data2 = pd.read_csv("data/kaggle_survey_2020_responses.csv")

In [ ]:
# 박사 학위 소지자들만 골라보자.
phds = data2[data2.iloc[:, 4] == "Doctoral degree"]
phds

In [ ]:
# 박사 학위 소지자들에 대한 정보만 kaggle_survey_2020_phd.csv로 다시 저장하자.
phds.to_csv("data/kaggle_survey_2020_phd.csv")

In [ ]:
# (OPTIONAL) 박사 학위 소지자이면서, 대한민국 국적을 가진 사람들을 뽑아보자.
data2[(data2["Q4"] == "Doctoral degree") & (data2["Q3"].isin(["Republic of Korea", "South Korea"]))]